-- 1. 매장 정보 테이블
create table locations (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision,
  lng double precision,
  region text default '제주',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 수거 기록 테이블
create table records (
  id bigint generated by default as identity primary key,
  location_id bigint references locations(id),
  weight double precision not null,
  week text not null, -- 예: '1주차', '2주차'
  month text not null, -- 예: '3월'
  collected_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 초기 매장 데이터 (기존 앱 데이터 기반)
insert into locations (name, lat, lng) values
('에이바우트커피 칠성점', 33.5135, 126.5273),
('에이바우트커피 관덕정점', 33.5115, 126.5238),
('에이바우트커피 시청점', 33.4996, 126.5312),
('에이바우트커피 법원점', 33.4948, 126.5356),
('에이바우트커피 중앙여고점', 33.4912, 126.5401),
('에이바우트커피 베라체점', 33.4885, 126.5445),
('에이바우트커피 인제점', 33.5052, 126.5428),
('에이바우트커피 삼화점', 33.5189, 126.5812),
('에이바우트커피 삼양점', 33.5224, 126.5867),
('에이바우트커피 도남점', 33.4921, 126.5289),
('에이바우트커피 연동점', 33.4856, 126.4923),
('에이바우트커피 신제주점', 33.4889, 126.4967),
('에이바우트커피 노형점', 33.4832, 126.4789),
('에이바우트커피 한라대점', 33.4798, 126.4745),
('에이바우트커피 외도점', 33.4956, 126.4321),
('에이바우트커피 하귀점', 33.4812, 126.4056),
('에이바우트커피 애월점', 33.4654, 126.3589),
('에이바우트커피 한림점', 33.4123, 126.2654),
('에이바우트커피 대정점', 33.2256, 126.2543),
('에이바우트커피 중문점', 33.2489, 126.4123),
('에이바우트커피 서귀포점', 33.2541, 126.5612),
('에이바우트커피 성산점', 33.4589, 126.9123),
('에이바우트커피 함덕점', 33.5412, 126.6689),
('에이바우트커피 조천점', 33.5356, 126.6345);

-- 4. RLS (Row Level Security) 정책 설정 (누구나 읽고 쓸 수 있게 설정 - 프로토타입용)
alter table locations enable row level security;
alter table records enable row level security;

create policy "Enable read access for all users" on locations for select using (true);
create policy "Enable insert access for all users" on locations for insert with check (true);

create policy "Enable read access for all users" on records for select using (true);
create policy "Enable insert access for all users" on records for insert with check (true);
